### ISSUE TITLE
Problem in iconv processes large input

### ISSUE THREAD

**Issue by jacktang** [edescourtis/iconverl#2]
Hi

I had tried both usages in README to process large input, and they were failed with {error,eilseq}. And my code look like
```
CD = iconverl:open("utf-8", "gb2312"),
{ok, NBin} = iconverl:conv(CD, LargeBin),
```
The LargeBin came from the response of http://stock.finance.qq.com/fund/jzzx/kfs.js?0.3069826727733016.

I read the code, line 60 in iconverl.erl seems it will chunk big input into pieces and collect the result. Would you tell me what I missed in this case? Thanks!

**Comment by edescourtis** [comment]
I will take a quick look.

**Comment by edescourtis** [comment]
eric@eric:~$ iconv -f gb2312 -t utf-8 iconv_gb2312.dat 
var v_kfs=[["110005","易方达积极成长混合","0.8887","-0.0073","-0.8147","4.5176","2015-03-26","开放","开放","王超"],["110007","易方达稳健收益债券A","1.2999","-0.0047","-0.3603","1.7235","2015-03-26","开放","开放","胡剑"],["110001","易方达平稳增长混合","2.1510","-0.0260","-1.1943","3.4360","2015-03-26","开放","开放","陈皓"],["110002","易方达策略成长混合","4.6310","0.0100","0.2164","6.0310","2015-03-26","开放","开放","蔡海洪"],["110003","易方达上证50指数","1.0504","0.0151","1.4585","2.9004","2015-03-26","开放","开放","林飞"],["110008","易方达稳健收益债券B","1.3021","-0.0047","-0.3597","1.7517","2015-03-26","开放","开放","胡剑"],["110009","易方达价值精选股票","1.4715","-0.0274","-1.8280","2.8585","2015-03-26","开放","开放","郑希"],["673010","西部利得新动向混合","1.4290","0.0000","0.0000","1.4290","2015-03-26","开放","开放","付琦"],["310388","申万菱信消费增长股票","1.5440","-0.0670","-4.1589","1.6420","2015-03-26","开放","开放","徐爽"],["519170","浦银安盛增长动力混合","1.0130","0.0130","1.3000","1.0130","2015-03-20","--","--","蒋建伟"],["000091","信诚新双盈分级债券","1.2500","-0.0030","-0.2394","1.2500","2015-03-26","--","--","王旭巍"],["000093","信诚新双盈分级债券B","1.3950","-0.0040","-0.2859","1.3950","2015-03-26","暂停","暂停","王旭巍"],["000092","信诚新双盈分级债券A","1.0100","0.0000","0.0000","1.0100","2015-03-26","暂停","暂停","王旭巍"],["000259","农银区间收益混合","1.4917","-0.0263","-1.7325","1.4917","2015-03-26","开放","开放","陈富权"],["000258","上投摩根岁岁盈定期开放债券C","1.0500","-0.0010","-0.0951","1.1000","2015-03-26","--","暂停","赵峰"],["000257","上投摩根岁岁盈定期开放债券A","1.0520","0.0000","0.0000","1.1060","2015-03-26","--","暂停","赵峰"],["000256","上投摩根红利回报混合","1.1130","0.0010","0.0899","1.2190","2015-03-26","暂停","开放","征茂平"],["000255","长城定期开放债券C","1.0740","-0.0010","-0.0930","1.1560","2015-03-26","暂停","暂停","钟光正"],["000254","长城定期开放债券A","1.0810","-0.0010","-0.0924","1.1630","2015-03-26","暂停","暂停","钟光正"],["000253","景顺长城景兴信用纯债债券C","1.1300","-0.0020","-0.1767","1.1300","2015-03-26","开放","开放","陈文鹏"],["000252","景顺长城景兴信用纯债债券A","1.1390","-0.0020","-0.1753","1.1390","2015-03-26","开放","开放","陈文鹏"],["000251","工银金融地产股票","2.5450","0.0030","0.1180","2.5450","2015-03-26","开放","开放","王君正"],["206018","鹏华产业债债券","1.1640","-0.0020","-0.1715","1.2100","2015-03-26","开放","开放","祝松"],["206011","鹏华美国房地产(QDII)","1.1110","-0.0200","-1.7683","1.2310","2015-03-25","开放","开放","裘韬"],["206010","鹏华深证民营ETF联接","1.4846","-0.0336","-2.2131","1.4846","2015-03-26","开放","开放","崔俊杰"],["206013","鹏华金刚保本混合","1.3270","-0.0100","-0.7479","1.3270","2015-03-26","开放","开放","戴钢"],["206012","鹏华价值精选股票","1.4580","-0.0120","-0.8163","1.4580","2015-03-26","开放","开放","彭建辉"],["206015","鹏华纯债债券","1.1160","-0.0080","-0.7117","1.2060","2015-03-26","开放","开放","刘太阳"],["150170","汇添富恒生指数分级(QDII)B","1.1580","-0.0040","-0.3442","1.1580","2015-03-26","--","--","赖中立"],["150171","申万菱信申银万国证券行业指数分级A","1.0021","0.0002","0.0200","1.0621","2015-03-26","--","--","张少华"],["150172","申万菱信申银万国证券行业指数分级B","1.1209","-0.0116","-1.0243","3.3071","2015-03-26","--","--","张少华"],["150173","信诚中证TMT产业主题指数分级A","1.0000","0.0000","0.0000","1.0190","2015-03-26","--","--","吴雅楠"],["150174","信诚中证TMT产业主题指数分级B","0.9240","-0.0760","-7.6000","1.9190","2015-03-26","--","--","吴雅楠"],["150175","银华恒生国企指数分级(QDII)A","1.0195","0.0002","0.0196","1.0605","2015-03-26","--","--","乐育涛"],["150176","银华恒生国企指数分级(QDII)B","1.2365","-0.0122","-0.9770","1.2365","2015-03-26","--","--","乐育涛"],["150177","鹏华证券保险分级A","1.0000","0.0000","0.0000","1.0530","2015-03-26","--","--","余斌"],["150178","鹏华证券保险分级B","0.9800","0.0060","0.6160","3.0680","2015-03-26","--","--","余斌"],["150179","鹏华信息分级A","1.0060","0.0000","0.0000","1.0530","2015-03-26","--","--","余斌"],["310358","申万菱信新经济混合","1.0644","-0.0473","-4.2547","2.3963","2015-03-26","开放","开放","徐爽"],["257020","国联安精选股票","1.1600","-0.0070","-0.5998","3.3690","2015-03-26","开放","开放","魏东"],["000150","华安双债添利债券C","1.2700","-0.0050","-0.3922","1.2700","2015-03-26","开放","开放","贺涛"],["000623","华富恒财分级债券A","1.0210","0.0000","0.0000","1.0530","2015-03-26","暂停","暂停","胡伟"],["585001","东吴中证新兴产业指数","1.3360","-0.0100","-0.7429","1.3360","2015-03-26","开放","开放","周健"],["166801","浙商聚潮新思维混合","2.0250","-0.0100","-0.4914","2.0250","2015-03-26","开放","开放","张文洁"],["166802","浙商沪深300指数分级","1.3620","0.0030","0.2208","1.4430","2015-03-26","开放","开放","关永祥"],["410009","华富量子生命力股票","1.1484","-0.0329","-2.7851","1.1484","2015-03-26","开放","开放","朱蓓"],["410008","华富中证100指数","1.1210","0.0102","0.9183","1.1210","2015-03-26","开放","开放","朱蓓"],["261101","景顺长城稳定收益债券C","1.0560","-0.0010","-0.0946","1.0660","2015-03-26","开放","开放","汝平"],["261102","景顺长城优信增利债券C","1.1650","-0.0050","-0.4274","1.1750","2015-03-26","开放","开放","陈文鹏"],["410003","华富成长趋势股票","1.0727","-0.0199","-1.8213","1.3627","2015-03-26","开放","开放","龚炜"],["410001","华富竞争力优选混合","1.0551","-0.0268","-2.4771","2.6735","2015-03-26","开放","开放","龚炜"],["410007","华富价值增长混合","1.5456","-0.0280","-1.7794","1.5456","2015-03-26","开放","开放","陈启明"],["410006","华富策略精选混合","1.4182","-0.0345","-2.3749","1.5782","2015-03-26","开放","开放","刘文正"],["410005","华富收益增强债券B","1.5885","0.0026","0.1639","1.8705","2015-03-26","开放","开放","胡伟"],["410004","华富收益增强债券A","1.5934","0.0026","0.1634","1.9054","2015-03-26","开放","开放","胡伟"],["167601","国金沪深300指数分级","1.0870","0.0024","0.2213","1.7239","2015-03-26","开放","开放","宫雪"],["100016","富国天源平衡混合","1.4282","-0.0439","-2.9821","3.1408","2015-03-26","开放","开放","曹晋"],["519191","万家城市建设主题纯债债券","1.0098","-0.0001","-0.0099","1.1314","2015-03-26","开放","开放","苏谋东"],["519190","万家岁得利定期开放债券","1.0408","0.0002","0.0192","1.1082","2015-03-26","开放","开放","孙驰"],["519192","万家市政纯债定期开放债券","1.0185","0.0000","0.0000","1.0614","2015-02-05","暂停","暂停","唐俊杰"],["100018","富国天利增长债券","1.2553","0.0010","0.0797","2.2583","2015-03-26","开放","开放","黄纪亮"],["510610","华夏能源ETF","1.0539","0.0337","3.3033","1.0539","2015-03-26","开放","开放","张弘iconv: illegal input sequence at position 6505

Looks like an error in the input encoding. Your data has some errors.

**Comment by edescourtis** [comment]
You can try this if you want to ignore the illegal characters:

```
CD = iconverl:open("utf-8//IGNORE", "gb2312"),
{ok, NBin} = iconverl:conv(CD, LargeBin),
```

**Comment by jacktang** [comment]
Thanks for the quick response :). And yes you are right, I changed GB2312 character set to GBK and it works.
